const char* shader_blurline_frag =

"#version 150\n"
"//\n"
"// Fragment Shader\n"
"//\n"
"\n"
"// uniform vec4 uColor;\n"
"uniform vec4  uColor;\n"
"varying vec2  vTextVary;    // Textur-Koordinaten\n"
"\n"
"\n"
"void main()\n"
"{\n"
"    const float klim = 0.9;\n"
"	if (vTextVary.x > klim)\n"
"	{\n"
"		gl_FragColor = uColor;		\n"
"	}\n"
"	else\n"
"	{\n"
"		float d = smoothstep(0.0, 1.0, vTextVary.x / klim);\n"
"		gl_FragColor = vec4(uColor.r, uColor.g, uColor.b, uColor.a * d);\n"
"	}\n"
"}\n"
"\n";
