const char* shader_blurline_frag =

"//\n"
"// Fragment Shader\n"
"//\n"
"\n"
"// uniform vec4 uColor;\n"
"uniform vec4  uColor;\n"
"varying vec2  vTextVary;    // Textur-Koordinaten\n"
"\n"
"\n"
"void main()\n"
"{\n"
"	float klim = 0.5;\n"
"   //gl_FragColor = uColor;\n"
"	if (vTextVary.x > klim)\n"
"	{\n"
"		gl_FragColor = uColor;\n"
"		//float d = klim; //+ (1.0 - (vTextVary.x * vTextVary.x));\n"
"		//gl_FragColor = vec4(uColor.r, uColor.g, uColor.b, uColor.a * d);\n"
"		\n"
"	}\n"
"	else\n"
"	{\n"
"		//float d = vTextVary.x / (klim * 1.2);\n"
"		float d = vTextVary.x / klim;\n"
"		d = d * d;\n"
"		gl_FragColor = vec4(uColor.r, uColor.g, uColor.b, uColor.a * d);\n"
"		//gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0);\n"
"	}\n"
"// 	gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0);\n"
"	\n"
"	\n"
"}\n"
"\n";
