const char* shader_noise_frag =

"//\n"
"// Fragment Textur Shader\n"
"//\n"
"\n"
"\n"
"\n"
"varying vec2      vTextVary;  // Textur-Koordinaten\n"
"uniform float     uSeed;\n"
"\n"
"\n"
"float rand(vec2 co)\n"
"{\n"
"  return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);\n"
"}\n"
"\n"
"\n"
"float Noise()\n"
"{\n"
"  vec3 col;\n"
"  vec2 seed;\n"
"  \n"
"  seed = fract(vTextVary.st * uSeed);\n"
"  \n"
"  return fract(rand(seed)) * 0.1;\n"
"}\n"
"\n"
"void main()\n"
"{ \n"
"  //gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); \n"
"	\n"
"	float tr = Noise(); //fract(100007.0 * vTextVary.x + vTextVary.y * uSeed);\n"
"\n"
"	//vec4 TexColor = texture2D(uTexture, vTextVary);\n"
"	//gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);\n"
" 	gl_FragColor = vec4(tr, tr, tr, 1.0);\n"
"}\n"
"\n";
